using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using SeatAllocationOptimizer.Main; // Add namespace for our new classes

// Defines a class for the main operations related to passenger and seat management.
public class MainClass
{
    // Constants for plane dimensions and seat calculations - Keep for now, might be used by Allocator constructor
    public static int planeWidth = 6; // Width of the plane in terms of seats per row - Note: SeatingAllocator uses seatsPerRow
    public static int planeRows = 3; // Number of rows in the plane - Note: SeatingAllocator uses planeRows
    public static int bonusSeats = 2; // Additional seats available - Note: SeatingAllocator doesn't explicitly use this concept currently
    public static int totalSeats = (planeRows * planeWidth) + bonusSeats; // Total number of seats - Note: SeatingAllocator calculates total internally

    // Main entry point for the program
    public static void Main(string[] args)
    {
        // Measure program execution time
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();

        Console.WriteLine("Starting Seating Allocation...");

        // --- New Logic using SeatAllocationOptimizer.Main classes ---

        // 1. Parse Input Data (using placeholder logic for now)
        // TODO: Update DataParser.ParseInput to read "Data/input.txt" properly
        string inputFile = "Data/input.txt";
        List<BoardingGroup> boardingGroups = DataParser.ParseInput(inputFile);

        // 2. Configure and run the Allocator
        // Using dimensions from constants - adjust if needed or pass via args
        // Note: The current SeatingAllocator doesn't use 'bonusSeats' directly.
        // The README mentioned 4 rows/5 seats initially, then 33 rows for 200 seats. Let's use the constants for now.
        int rows = planeRows;
        int seatsPerRow = planeWidth;
        // If totalSeats implies a different layout (e.g., including bonus seats), adjust rows/seatsPerRow calculation needed.
        // For now, using the defined rows and width.
        var allocator = new SeatingAllocator(planeRows: rows, seatsPerRow: seatsPerRow);

        // 3. Allocate Seats
        SeatingAllocator.AllocationResult result = allocator.AllocateSeats(boardingGroups);

        // 4. Print Results (using Allocator's methods)
        allocator.PrintSeatingMap(); // Prints the map generated by the allocator
        Console.WriteLine($"Total Calculated Revenue: {result.TotalRevenue:C}");
        if (result.UnseatedGroups.Any())
        {
            Console.WriteLine($"Number of unseated groups: {result.UnseatedGroups.Count}");
            // Optionally print details about unseated groups
        }

        // --- End New Logic ---


        // Stop measuring time
        stopwatch.Stop();

        // Print memory usage and time taken
        PrintMemoryUsage(stopwatch);
    }

    // Function to print memory usage - Keep this utility
    public static void PrintMemoryUsage(Stopwatch stopwatch)
    {
        long memoryUsed = GC.GetTotalMemory(false);
        Console.WriteLine($"Memory used: {memoryUsed / 1024} KB");
        Console.WriteLine($"Time taken: {stopwatch.Elapsed}");
    }

    /* --- Commenting out Old Logic ---

    // Prints the seating arrangement in the console
    public static void printMap(Passenger[,] seatMap)
    {
        // ... (old implementation) ...
    }

    // Calculate and return total revenue from the seat map
    public static double calculateRevenue(Passenger[,] seatMap)
    {
        // ... (old implementation) ...
    }

    // Helper method to set up boarding groups from passenger list
    public static PriorityQueue<BoardingGroup, BoardingGroup> dataSetupHelper(List<Passenger> passengers)
    {
        // ... (old implementation, uses different Passenger/Family/BoardingGroup) ...
    }

    // Determines the ideal seating arrangement for maximum revenue
    public static Passenger[,] idealRevenue(PriorityQueue<BoardingGroup, BoardingGroup> boardingGroups)
    {
         // ... (old implementation) ...
    }

    // Processes each boarding group to fit into the seating map
    public static Passenger[,] processBoardingGroup(Passenger[,] seatMap, BoardingGroup bg, int curRow, int curRowSeat, int maxSeatsPerRow)
    {
         // ... (old implementation) ...
    }

    */ // --- End Commented Out Old Logic ---

}

// Note: The original file also had definitions for Passenger, Family, BoardingGroup, BoardingGroupComparator classes.
// These might be defined within this file below the MainClass, or in separate files (e.g., in Entities/).
// If they are in separate files, those files might need to be removed or refactored if they conflict with the new classes.
// For now, we've focused on replacing the logic within MainClass.

